CREATE DATABASE UPAX_SYSTEM;

USE UPAX_SYSTEM;

CREATE TABLE usuario(
Pk_usuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
usuario VARCHAR(50) NOT NULL,
contrasena VARCHAR(30) NOT NULL,
nombre VARCHAR(50),
a_materno VARCHAR(50),
a_paterno VARCHAR(50)
);
